project_name: opendog
builds:
  - binary: opendog
    goos:
      - darwin
      - linux
    goarch:
      - arm64
      - amd64
archives:
  - files:
      - README.md
release:
  github:
    owner: vend
    name: opendog
  prerelease: auto